
name: tf-checkov-action
on:
  # push:
  #   paths:
  #     - 'tf_code**'
  #   branches:
  #     - develop
  #     - main
  workflow_call:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  tf-Checkov-action:
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    runs-on: [ linux ]
    name: tf-Checkov-action
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          node-version: '16'
      - name: Branch name
        run: echo "running on branch ${GITHUB_REF##*/}"

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: test
          framework: terraform
          check: MEDIUM,HIGH

